# Generated by Django 3.0.2 on 2020-02-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.TextField(choices=[('capitalone', 'Capital One'), ('citi', 'Citi'), ('chase', 'Chase'), ('discover', 'Discover')], unique=True),
        ),
    ]
